# Generated by Django 5.1.15 on 2026-04-27 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('size', models.BigIntegerField(default=0)),
                ('content_type', models.CharField(blank=True, default='', max_length=255)),
                ('provider', models.CharField(max_length=64)),
                ('provider_file_id', models.CharField(blank=True, db_index=True, max_length=512, null=True)),
                ('url', models.URLField(blank=True, max_length=2048, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('uploading', 'Uploading'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('error_message', models.TextField(blank=True, default='')),
                ('owner', models.CharField(db_index=True, default='default', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('temp_path', models.CharField(blank=True, default='', max_length=1024)),
                ('upload_strategy', models.CharField(blank=True, default='', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['owner', 'provider'], name='storage_fil_owner_032b6d_idx'), models.Index(fields=['status'], name='storage_fil_status_82a953_idx')],
            },
        ),
        migrations.CreateModel(
            name='StorageCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(db_index=True, max_length=255)),
                ('provider', models.CharField(max_length=64)),
                ('credentials', models.JSONField(default=dict)),
                ('is_default', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('owner', 'provider'),
                'constraints': [models.UniqueConstraint(fields=('owner', 'provider'), name='uniq_owner_provider_credential')],
            },
        ),
    ]
